# BoardConfig for Snapdragon 632 / MSM8953 family

DEVICE_PATH := device/xiaomi/onc

TARGET_ARCH := arm64
TARGET_ARCH_VARIANT := armv8-a
TARGET_CPU_ABI := arm64-v8a
TARGET_CPU_ABI2 :=
TARGET_CPU_VARIANT := generic

TARGET_2ND_ARCH := arm
TARGET_2ND_ARCH_VARIANT := armv7-a-neon
TARGET_2ND_CPU_ABI := armeabi-v7a
TARGET_2ND_CPU_ABI2 := armeabi
TARGET_2ND_CPU_VARIANT := generic

TARGET_BOARD_PLATFORM := msm8953
TARGET_BOARD_PLATFORM_GPU := qcom-adreno506
TARGET_BOOTLOADER_BOARD_NAME := onc

BOARD_KERNEL_CMDLINE := console=ttyMSM0,115200,n8 androidboot.hardware=qcom androidboot.console=ttyMSM0 user_debug=31 msm_rtb.filter=0x237 ehci-hcd.park=3
BOARD_KERNEL_BASE := 0x80000000
BOARD_KERNEL_PAGESIZE := 4096

BOARD_FLASH_BLOCK_SIZE := 131072
BOARD_BOOTIMAGE_PARTITION_SIZE := 67108864
BOARD_RECOVERYIMAGE_PARTITION_SIZE := 67108864

TARGET_NO_KERNEL := false
TARGET_NO_RECOVERY := false

# Fill the exact partition sizes from the real stock firmware
# BOARD_SYSTEMIMAGE_PARTITION_SIZE :=
# BOARD_VENDORIMAGE_PARTITION_SIZE :=
# BOARD_USERDATAIMAGE_PARTITION_SIZE :=
# BOARD_DTBOIMAGE_PARTITION_SIZE :=

BOARD_USES_QCOM_HARDWARE := true
BOARD_HAVE_BLUETOOTH := true
TARGET_USERIMAGES_USE_EXT4 := true
TARGET_USERIMAGES_USE_F2FS := true
BOARD_SYSTEMIMAGE_FILE_SYSTEM_TYPE := ext4
BOARD_VENDORIMAGE_FILE_SYSTEM_TYPE := ext4
BOARD_USES_GENERIC_AUDIO := false

TARGET_USES_64_BIT_BINDER := true
TARGET_SUPPORTS_64_BIT_APPS := true
TARGET_USES_QCOM_BSP := true

# These will be refined after the stock firmware partition layout is studied
# BOARD_ROOT_EXTRA_FOLDERS :=
